global:
  security:
    allowInsecureImages: true
image:
  registry: docker.io
  repository: bitnamilegacy/redis
fullnameOverride: kzero-probe-redis
architecture: standalone
auth:
  enabled: false
master:
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
replica:
  replicaCount: 0
